# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.3 -g --silent

# add app
COPY . ./

# start app
CMD ["npm", "start"]

# funcionou
# docker build -t hesete/react-shogi .
# docker run -it --rm -p 3001:3000 hesete/react-shogi

# docker login registry.gitlab.com
# docker build -t registry.gitlab.com/hesete/react-shogi .
# docker push registry.gitlab.com/hesete/react-shogi

# docker pull registry.gitlab.com/hesete/react-shogi
